service: aws-java-simple-http-endpoint
frameworkVersion: '3'

provider:
  name: aws
  runtime: java17

package:
  artifact: target/aws-java-simple-http-endpoint.jar

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /time
          method: get
